[theme]
primaryColor = "#64ffda"
backgroundColor = "#0a192f"
secondaryBackgroundColor = "#112240"
textColor = "#ccd6f6"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
